### ISSUE TITLE
Support Meteor 1.4

### ISSUE THREAD

**Issue by Ulexus** [CyCoreSystems/docker-meteor#21]
Meteor 1.4 changes the build process and uses NodeJS stable (finally!).

**Comment by Ulexus** [comment]
I have pushed the `v1.4` tag to Docker.  Anyone interested, please test with this tag:  `ulexus/meteor:v1.4`

**Comment by maxfriedmann** [comment]
Hi @Ulexus,
I just tried using the tag 1.4 and am getting the famous error below : 

```
2016-08-04T15:36:56.694883357Z /var/www/bundle/programs/server/node_modules/fibers/future.js:280
2016-08-04T15:36:56.694920071Z 	throw(ex);
2016-08-04T15:36:56.694931126Z 	^
2016-08-04T15:36:56.694940548Z 
2016-08-04T15:36:56.694948885Z Error: Module did not self-register.
2016-08-04T15:36:56.694957502Z     at Error (native)
2016-08-04T15:36:56.694968856Z     at Object.Module._extensions..node (module.js:434:18)
2016-08-04T15:36:56.694978194Z     at Module.load (module.js:343:32)
2016-08-04T15:36:56.694986518Z     at Module.Mp.load (/var/www/bundle/programs/server/npm/node_modules/meteor/babel-compiler/node_modules/reify/node/runtime.js:16:23)
2016-08-04T15:36:56.694995051Z     at Function.Module._load (module.js:300:12)
2016-08-04T15:36:56.695003513Z     at Module.require (module.js:353:17)
2016-08-04T15:36:56.695011922Z     at require (internal/module.js:12:17)
2016-08-04T15:36:56.695020681Z     at bindings (/var/www/bundle/programs/server/npm/node_modules/meteor/npm-bcrypt/node_modules/bindings/bindings.js:76:44)
2016-08-04T15:36:56.695029383Z     at Object.<anonymous> (/var/www/bundle/programs/server/npm/node_modules/meteor/npm-bcrypt/node_modules/bcrypt/bcrypt.js:3:35)
2016-08-04T15:36:56.695171991Z     at Module._compile (module.js:409:26)
```

After a not so graceful restart the container hangs on "Starting Meteor Application...". Any ideas?

Here's the complete log : 

```
2016-08-04T15:45:57.465585212Z Downloading Application bundle from https://s3.eu-central-1.amazonaws.com/(...).tar.gz...
2016-08-04T15:45:57.483700628Z   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
2016-08-04T15:45:57.483999313Z                                  Dload  Upload   Total   Spent    Left  Speed
2016-08-04T15:45:59.627773819Z    0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0  16 22.9M   16 3807k    0     0  8819k      0  0:00:02 --:--:--  0:00:02 8813k  65 22.9M   65 14.9M    0     0  10.4M      0  0:00:02  0:00:01  0:00:01 10.4M 100 22.9M  100 22.9M    0     0  10.7M      0  0:00:02  0:00:02 --:--:-- 10.7M
2016-08-04T15:46:02.184962769Z /var/www/bundle/programs/server /
2016-08-04T15:46:02.185058241Z Checking Meteor version...
2016-08-04T15:46:02.287324432Z 1.4.0
2016-08-04T15:46:02.290737921Z Installing NPM prerequisites...
2016-08-04T15:46:02.891799337Z npm WARN package.json meteor-dev-bundle@0.0.0 No description
2016-08-04T15:46:02.892224446Z npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
2016-08-04T15:46:02.893274847Z npm WARN package.json meteor-dev-bundle@0.0.0 No README data
2016-08-04T15:46:02.893551211Z npm WARN package.json meteor-dev-bundle@0.0.0 No license field.
2016-08-04T15:46:04.837519990Z 
2016-08-04T15:46:04.837560194Z > fibers@1.0.13 install /var/www/bundle/programs/server/node_modules/fibers
2016-08-04T15:46:04.837572660Z > node build.js || nodejs build.js
2016-08-04T15:46:04.837582529Z 
2016-08-04T15:46:04.927249073Z `linux-x64-v8-4.5` exists; testing
2016-08-04T15:46:05.027431169Z Binary is fine; exiting
2016-08-04T15:46:05.036473889Z npm WARN cannot run in wd meteor-dev-bundle@0.0.0 node npm-rebuild.js (wd=/var/www/bundle/programs/server)
2016-08-04T15:46:05.086530545Z ansi-styles@1.1.0 node_modules/ansi-styles
2016-08-04T15:46:05.086635196Z 
2016-08-04T15:46:05.086697559Z ansi-regex@0.2.1 node_modules/ansi-regex
2016-08-04T15:46:05.086717809Z 
2016-08-04T15:46:05.086736789Z escape-string-regexp@1.0.5 node_modules/escape-string-regexp
2016-08-04T15:46:05.086767392Z 
2016-08-04T15:46:05.086785121Z chalk@0.5.1 node_modules/chalk
2016-08-04T15:46:05.086803188Z 
2016-08-04T15:46:05.086820754Z amdefine@1.0.0 node_modules/amdefine
2016-08-04T15:46:05.086838782Z 
2016-08-04T15:46:05.086856365Z supports-color@0.2.0 node_modules/supports-color
2016-08-04T15:46:05.086874034Z 
2016-08-04T15:46:05.086891050Z strip-ansi@0.3.0 node_modules/strip-ansi
2016-08-04T15:46:05.086908333Z 
2016-08-04T15:46:05.086928712Z has-ansi@0.1.0 node_modules/has-ansi
2016-08-04T15:46:05.086945848Z 
2016-08-04T15:46:05.086962881Z underscore@1.5.2 node_modules/underscore
2016-08-04T15:46:05.087008809Z 
2016-08-04T15:46:05.087026820Z eachline@2.3.3 node_modules/eachline
2016-08-04T15:46:05.087043843Z 
2016-08-04T15:46:05.087060707Z type-of@2.0.1 node_modules/type-of
2016-08-04T15:46:05.087084470Z 
2016-08-04T15:46:05.087104408Z meteor-promise@0.7.2 node_modules/meteor-promise
2016-08-04T15:46:05.087121843Z 
2016-08-04T15:46:05.087138816Z asap@2.0.4 node_modules/asap
2016-08-04T15:46:05.087177345Z 
2016-08-04T15:46:05.087199068Z semver@4.1.0 node_modules/semver
2016-08-04T15:46:05.087216448Z 
2016-08-04T15:46:05.087233664Z source-map-support@0.3.2 node_modules/source-map-support
2016-08-04T15:46:05.087251095Z 
2016-08-04T15:46:05.087267939Z source-map@0.1.32 node_modules/source-map
2016-08-04T15:46:05.087284517Z 
2016-08-04T15:46:05.087300974Z promise@7.1.1 node_modules/promise
2016-08-04T15:46:05.087317750Z 
2016-08-04T15:46:05.087334537Z fibers@1.0.13 node_modules/fibers
2016-08-04T15:46:05.105247954Z /
2016-08-04T15:46:05.105562283Z Starting Meteor Application...
2016-08-04T15:46:07.446922588Z /var/www/bundle/programs/server/node_modules/fibers/future.js:280
2016-08-04T15:46:07.447000568Z 	throw(ex);
2016-08-04T15:46:07.447031510Z 	^
2016-08-04T15:46:07.447058089Z 
2016-08-04T15:46:07.447079639Z Error: Module did not self-register.
2016-08-04T15:46:07.447102634Z     at Error (native)
2016-08-04T15:46:07.447125993Z     at Object.Module._extensions..node (module.js:434:18)
2016-08-04T15:46:07.447149167Z     at Module.load (module.js:343:32)
2016-08-04T15:46:07.447194386Z     at Module.Mp.load (/var/www/bundle/programs/server/npm/node_modules/meteor/babel-compiler/node_modules/reify/node/runtime.js:16:23)
2016-08-04T15:46:07.447215178Z     at Function.Module._load (module.js:300:12)
2016-08-04T15:46:07.447233903Z     at Module.require (module.js:353:17)
2016-08-04T15:46:07.447252967Z     at require (internal/module.js:12:17)
2016-08-04T15:46:07.447272481Z     at bindings (/var/www/bundle/programs/server/npm/node_modules/meteor/npm-bcrypt/node_modules/bindings/bindings.js:76:44)
2016-08-04T15:46:07.447292615Z     at Object.<anonymous> (/var/www/bundle/programs/server/npm/node_modules/meteor/npm-bcrypt/node_modules/bcrypt/bcrypt.js:3:35)
2016-08-04T15:46:07.447495101Z     at Module._compile (module.js:409:26)
2016-08-04T15:46:10.716006679Z Downloading Application bundle from https://s3.eu-central-1.amazonaws.com/(...).tar.gz...
2016-08-04T15:46:10.732072215Z   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
2016-08-04T15:46:10.732354972Z                                  Dload  Upload   Total   Spent    Left  Speed
2016-08-04T15:46:13.114204992Z    0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0  41 22.9M   41 9808k    0     0  8288k      0  0:00:02  0:00:01  0:00:01 8284k  90 22.9M   90 20.7M    0     0  9732k      0  0:00:02  0:00:02 --:--:-- 9729k 100 22.9M  100 22.9M    0     0  9882k      0  0:00:02  0:00:02 --:--:-- 9882k
2016-08-04T15:46:16.668248493Z /var/www/bundle/programs/server /
2016-08-04T15:46:16.668467759Z Checking Meteor version...
2016-08-04T15:46:16.771704192Z 1.4.0
2016-08-04T15:46:16.775143305Z Installing NPM prerequisites...
2016-08-04T15:46:17.357790354Z npm WARN package.json meteor-dev-bundle@0.0.0 No description
2016-08-04T15:46:17.358218214Z npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
2016-08-04T15:46:17.359294916Z npm WARN package.json meteor-dev-bundle@0.0.0 No README data
2016-08-04T15:46:17.359684132Z npm WARN package.json meteor-dev-bundle@0.0.0 No license field.
2016-08-04T15:46:18.571794157Z npm WARN cannot run in wd meteor-dev-bundle@0.0.0 node npm-rebuild.js (wd=/var/www/bundle/programs/server)
2016-08-04T15:46:18.653678562Z /
2016-08-04T15:46:18.654185494Z Starting Meteor Application...
```

**Comment by Ulexus** [comment]
It looks like I missed the removal of the fibers version kludge.  I wonder why it worked on my own installations...  oh, well.  This should now be fixed, as of fcbd73ccc6502db9019705ec79936b5db974a541

**Comment by maxfriedmann** [comment]
Thanks for the quick reply! Now I unfortunately get this error : 

```
2016-08-04T21:16:06.263305992Z gyp ERR! build error 
2016-08-04T21:16:06.265011856Z gyp ERR! stack Error: not found: make
2016-08-04T21:16:06.265332124Z gyp ERR! stack     at F (/usr/lib/node_modules/npm/node_modules/which/which.js:63:19)
2016-08-04T21:16:06.266391476Z gyp ERR! stack     at E (/usr/lib/node_modules/npm/node_modules/which/which.js:72:29)
2016-08-04T21:16:06.266780263Z gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/which.js:81:16
2016-08-04T21:16:06.267704614Z gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/node_modules/isexe/index.js:44:5
2016-08-04T21:16:06.267716234Z gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/node_modules/isexe/mode.js:8:5
2016-08-04T21:16:06.267720833Z gyp ERR! stack     at Object.oncomplete (fs.js:108:15)
2016-08-04T21:16:06.267724152Z gyp ERR! System Linux 3.13.0-85-generic
2016-08-04T21:16:06.267727671Z gyp ERR! command "node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--release"
2016-08-04T21:16:06.268099432Z gyp ERR! cwd /var/www/bundle/programs/server/node_modules/fibers
2016-08-04T21:16:06.268345923Z gyp ERR! node -v v0.10.46
2016-08-04T21:16:06.268613222Z gyp ERR! node-gyp -v v3.3.1
2016-08-04T21:16:06.268837724Z gyp ERR! not ok 
2016-08-04T21:16:06.273308107Z node-gyp exited with code: 1
2016-08-04T21:16:06.273321106Z Please make sure you are using a supported platform and node version. If you
2016-08-04T21:16:06.273325471Z would like to compile fibers on this machine please make sure you have setup your
2016-08-04T21:16:06.273328646Z build environment--
```

I am running your container via docker cloud on an AWS EC2 instance.

**Comment by maxfriedmann** [comment]
wtf, node v0.10.46, maybe I am doing something wrong?

**Comment by Ulexus** [comment]
No, it looks like I screwed up somewhere; I must have mixed up my branches.

**Comment by Ulexus** [comment]
I somehow managed to completely wipe out my changes.  Oh, well.  Luckily, I was able to recover the script from one of my running services.

Restored and pushed to Docker Hub:  0eb9ef71bf83244a34df10b1e6e1be14dc1bbb89

Unfortunately, this means my earlier diagnosis of the problem was likely incorrect, since the correct script clearly shows I _had_ removed the fibers kludge already.

**Comment by maxfriedmann** [comment]
ok, so if the changes are in the build 9 minutes ago, something is still not working. Am back on : 

```
2016-08-04T21:43:26.607328694Z fibers@1.0.13 node_modules/fibers
2016-08-04T21:43:26.616200064Z /
2016-08-04T21:43:26.616410126Z Starting Meteor Application...
2016-08-04T21:43:28.621803776Z /var/www/bundle/programs/server/node_modules/fibers/future.js:280
2016-08-04T21:43:28.621836778Z 	throw(ex);
2016-08-04T21:43:28.621852751Z 	^
2016-08-04T21:43:28.621867165Z 
2016-08-04T21:43:28.621888329Z Error: Module did not self-register.
2016-08-04T21:43:28.621892855Z     at Error (native)
2016-08-04T21:43:28.621895811Z     at Object.Module._extensions..node (module.js:434:18)
2016-08-04T21:43:28.621900065Z     at Module.load (module.js:343:32)
2016-08-04T21:43:28.621903305Z     at Module.Mp.load (/var/www/bundle/programs/server/npm/node_modules/meteor/babel-compiler/node_modules/reify/node/runtime.js:16:23)
2016-08-04T21:43:28.621906465Z     at Function.Module._load (module.js:300:12)
2016-08-04T21:43:28.621911382Z     at Module.require (module.js:353:17)
2016-08-04T21:43:28.621914254Z     at require (internal/module.js:12:17)
2016-08-04T21:43:28.621917548Z     at bindings (/var/www/bundle/programs/server/npm/node_modules/meteor/npm-bcrypt/node_modules/bindings/bindings.js:76:44)
2016-08-04T21:43:28.621921728Z     at Object.<anonymous> (/var/www/bundle/programs/server/npm/node_modules/meteor/npm-bcrypt/node_modules/bcrypt/bcrypt.js:3:35)
2016-08-04T21:43:28.621965128Z     at Module._compile (module.js:409:26)
```

**Comment by Ulexus** [comment]
Yeah, all I did was revert to the original v1.4 version, so I would expect you to be back where you started.

Are you, by chance, creating your Meteor bundle on a different architecture than the one on which you are deploying?  There are a bunch of changes in v1.4 related to ABI compatibility, though as best I could tell, it seemed that running `npm install` should resolve them.  Perhaps it does not, entirely?

**Comment by maxfriedmann** [comment]
I create bundles with the "--architecture os.linux.x86_64" option, assuming that would work, even with meteor 1.4! 

I'll do a build on OSX and Ubuntu to see the differences!

**Comment by maxfriedmann** [comment]
Nope, same issues on all operation systems. How do you build the bundles that are working?

**Comment by Ulexus** [comment]
I'm not doing anything fancy:

```
  meteor build --directory .deploy/
```

The `.deploy` is arbitrary.

**Comment by Ulexus** [comment]
Can you post the Docker command you are using to execute (and any relevant environment variables)?

**Comment by maxfriedmann** [comment]
I am using the docker image via docker cloud and don't add any extra variables, except BUNDLE_URL, ROOT_URL and MONGO_URL.

**Comment by Ulexus** [comment]
@maxfriedmann Could you supply the output of `meteor list`?

**Comment by maxfriedmann** [comment]
I fear that won't help you any further since all direct depenencies are from out product : 

```
max-macbook-osx% meteor list
smallstack:analytics                 0.6.0-SNAPSHOT+ smallstack analytics package
smallstack:analytics-backoffice      0.6.0-SNAPSHOT+ smallstack analytics backoffice package
smallstack:angular-core              0.6.0-SNAPSHOT+ smallstack angular core package
smallstack:angular-login             0.6.0-SNAPSHOT+ smallstack angular login package
smallstack:angular-messaging         0.6.0-SNAPSHOT+ smallstack angular messaging package
smallstack:backoffice                0.6.0-SNAPSHOT+ smallstack backoffice package
smallstack:bootstrap                 0.6.0-SNAPSHOT+ smallstack bootstrap theme package
smallstack:cms                       0.6.0-SNAPSHOT+ smallstack cms package
smallstack:cms-backoffice            0.6.0-SNAPSHOT+ smallstack cms package
smallstack:cms-components            0.6.0-SNAPSHOT+ smallstack cms package
smallstack:collections               0.6.0-SNAPSHOT+ smallstack collections and models package
smallstack:collections-backoffice    0.6.0-SNAPSHOT+ smallstack analytics backoffice package
smallstack:configuration             0.6.0-SNAPSHOT+ smallstack configuration package
smallstack:configuration-backoffice  0.6.0-SNAPSHOT+ smallstack configuration backoffice package
smallstack:core                      0.6.0-SNAPSHOT+ smallstack core package
smallstack:hotcode-push              0.6.0-SNAPSHOT+ smallstack hot code push package
smallstack:i18n                      0.6.0-SNAPSHOT+ project bootstrapper i18n package
smallstack:i18n-backoffice           0.6.0-SNAPSHOT+ smallstack i18n backoffice package
smallstack:location                  0.6.0-SNAPSHOT+ smallstack location services package
smallstack:media                     0.6.0-SNAPSHOT+ smallstack media package
smallstack:navigation                0.6.0-SNAPSHOT+ smallstack navigation package
smallstack:navigation-backoffice     0.6.0-SNAPSHOT+ smallstack navigation backoffice package
smallstack:notifications             0.6.0-SNAPSHOT+ smallstack notifications package
smallstack:testdata                  0.6.0-SNAPSHOT+ smallstack helpers package
smallstack:user                      0.6.0-SNAPSHOT+ smallstack user services package
smallstack:utils                     0.6.0-SNAPSHOT+ smallstack helpers package
```

**Comment by Ulexus** [comment]
Alas, no.  Those do not appear to be publicly-available packages.  I have been unable to recreate your problem.  I have only Linux computers available, so I cannot test cross-architecture builds.

Could you try building the default Meteor demo application that you get with `meteor create`, and see if that fails for you, as well?

**Comment by athyuttamre** [comment]
I'm getting the same issue `Error: Module did not self-register.` :( I'm on Meteor 1.3.4 though, and using the v1.4 tag.

**Comment by Ulexus** [comment]
@athyuttamre That will definitely not work.  The v1.4 tag is not backward-compatible with previous versions of Meteor.  I've made some attempts at it, but it just doesn't work.  That's why I haven't made v1.4 the `latest` tag yet.

**Comment by athyuttamre** [comment]
Gotcha makes sense. I wonder if we could simply perform different build steps after detecting the version of the app? That way we wouldn't have to maintain two releases.

**Comment by Ulexus** [comment]
The problem is fairly fundamental:  they use different versions of NodeJS.  We could use something like node version manager, but then we would have to either store both versions in the container image or download them on each execution.

**Comment by athyuttamre** [comment]
Right, fair. I think downloading the Node version dynamically makes sense, rather than packaging it with the image. Any thoughts against that?

**Comment by Ulexus** [comment]
@athyuttamre That would cause the startup times to be very long.  Meteor is already very slow to start (if you don't run with a pre-bundled distribution), and I really don't want to have to wait on Node to be installed, as well.

We could do something like that for backward compatibility, but I don't really think it is worth the work.  It is easy enough to just use the legacy tag instead.

**Comment by abate** [comment]
Same problem here : 

> Checking Meteor version...
> 1.4.1
> Installing NPM prerequisites...
> npm WARN package.json meteor-dev-bundle@0.0.0 No description
> npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
> npm WARN package.json meteor-dev-bundle@0.0.0 No README data
> npm WARN package.json meteor-dev-bundle@0.0.0 No license field.
> npm WARN cannot run in wd meteor-dev-bundle@0.0.0 node npm-rebuild.js (wd=/var/www/bundle/programs/server)
> /
> Starting Meteor Application...
> /var/www/bundle/programs/server/node_modules/fibers/fibers.js:16
>   throw new Error('`'+ modPath+ '.node` is missing. Try reinstalling `node-fibers`?');
>   ^
>  
> Error: `/var/www/bundle/programs/server/node_modules/fibers/bin/linux-x64-v8-4.5/fibers.node` is missing. Try reinstalling `node-fibers`?
>     at Object.<anonymous> (/var/www/bundle/programs/server/node_modules/fibers/fibers.js:16:8)
>     at Module._compile (module.js:409:26)
>     at Object.Module._extensions..js (module.js:416:10)
>     at Module.load (module.js:343:32)
>     at Function.Module._load (module.js:300:12)
>     at Module.require (module.js:353:17)
>     at require (internal/module.js:12:17)
>     at Object.<anonymous> (/var/www/bundle/programs/server/boot.js:1:75)
>     at Module._compile (module.js:409:26)
>     at Object.Module._extensions..js (module.js:416:10)

and this is the list of my dependencies : 

```
accounts-base                       1.2.11  A user account system
accounts-password                   1.3.0  Password support for accounts
alanning:roles                      1.2.14+ Authorization package for Meteor
aldeed:autoform                     5.8.1  Easily create forms with automatic insert and up...
aldeed:collection2                  2.10.0  Automatic validation of insert and update opera...
aldeed:template-extension           4.0.0  Adds template features currently missing from th...
anti:fake                           0.4.1  Random text and data generator
aslagle:reactive-table              0.8.34  A reactive table designed for Meteor
blaze-html-templates                1.0.5  Compile HTML templates into reactive UI with Met...
check                               1.2.3  Check whether a value matches a pattern
chhib:selectize-bootstrap-3         0.0.1  Selectize is a hybrid of a textbox and <select> ...
cmather:handlebars-server           0.2.0* Allows handlebars templates to be defined on the...
coffeescript                        1.2.4_1* Javascript dialect with fewer braces and semic...
comerc:autoform-selectize           2.3.2  Custom "selectize" input type for AutoForm
cunneen:mailgun                     0.9.1  Easily send emails using Mailgun as your email p...
dburles:collection-helpers          1.0.4  Transform your collections with helpers that you...
dburles:factory                     0.4.2* Factories for Meteor
ejson                               1.0.12  Extended and Extensible JSON library
froatsnook:valid-email              1.0.0  Validate email addresses.
gwendall:impersonate                0.2.2  Impersonate users in Meteor
iron:router                         1.0.13  Routing specifically designed for Meteor
jeremy:selectize                    0.12.1_5  Selectize is a hybrid of a textbox and <selec...
jquery                              1.11.9  Manipulate the DOM using CSS selectors
juliancwirko:s-alert                3.2.0  Simple and fancy notifications / alerts / errors...
less                                2.7.5  Leaner CSS language
logging                             1.1.15  Logging facility.
matb33:collection-hooks             0.8.4  Extends Mongo.Collection with before/after hooks...
meteor-base                         1.0.4  Packages that every Meteor app needs
mobile-experience                   1.0.4  Packages for a great mobile user experience
momentjs:moment                     2.15.1  Moment.js (official): parse, validate, manipula...
mongo                               1.1.12  Adaptor for using MongoDB and Minimongo over DDP
mousetrap:mousetrap                 1.4.6_1  Mousetrap (official): bind, trigger and handle...
ongoworks:security                  2.0.1  Logical security for client-originated MongoDB c...
ostrio:autoform-files               1.0.7  File upload for AutoForm using ostrio:files
ostrio:files                        1.7.3  Upload files via DDP, HTTP and WebRTC/DC. To ser...
raix:handlebar-helpers              0.2.5  Handlebar helpers
random                              1.0.10  Random number generator and utilities
reactive-var                        1.0.10  Reactive variable
reload                              1.1.10  Reload the page while preserving application st...
reywood:publish-composite           1.4.2  Publish a set of related documents from multiple...
session                             1.1.6  Session variable
shell-server                        0.2.1  Server-side component of the `meteor shell` comm...
softwarerero:accounts-t9n           1.3.5  Almost i18n, with standard translations for basi...
spacebars                           1.0.13  Handlebars-like template language for Meteor
standard-minifier-css               1.2.1  Standard css minifier used with Meteor apps by d...
standard-minifier-js                1.2.0  Standard javascript minifiers used with Meteor a...
tracker                             1.1.0  Dependency tracker to allow reactive callbacks
underscorestring:underscore.string  3.3.4  underscore.string (official): String manipulatio...
useraccounts:bootstrap              1.14.2  Accounts Templates styled for Twitter Bootstrap.
useraccounts:iron-routing           1.14.2  UserAccounts package providing routes configura...
yasinuslu:blaze-meta                0.3.3  Blaze-meta makes it super simple to manage SEO d...
zimme:iron-router-active            1.0.4* Active route/path template helpers for iron:router
```

and this is my docker-compose file

```
ksp:
    image: ulexus/meteor:v1.4
    restart: always
    ports:
        - "8081:80"
    links:
        - mongodb
    volumes:
        - /home/ksp/app:/var/www
    environment:
        - MONGO_URL=mongodb://mongodb/ksp
        - ROOT_URL=http://test.mooo.com
        - APP_DIR=/var/www
        - DELAY=30
mongodb:
    image: mongo
    ports:
        - "27017:27017"
```

I hope this helps ...

**Comment by Ulexus** [comment]
You are binding your source tree to the bundle directory.  Are you sure you bundled for the correct architecture?  Otherwise, mount the application source directory to `/src/app`

**Comment by abate** [comment]
I guess something was wrong with the bundle even though the architecture on the dev machine and my server is the same. I've tried with the REPO option and it is working now. I wanted to use the bundle to reduce the start-up time and to hot push my code. I guess this is not possible with the REPO option. thank you for the quick answer !

**Comment by Ulexus** [comment]
@abate it is certainly possible, as that is what I do.  I have not run into your problem, though.  The architecture difference is my best guess, but it is certainly possible something else is the culprit.

**Comment by Ulexus** [comment]
pre-1.4 has now been moved to the `legacy` branch and the `legacy` tag.  `latest` and `master, respectively now point to the 1.4-compatible release.
