### ISSUE TITLE
Error during the launch of nodejs

### ISSUE THREAD

**Issue by Antoine-O** [CyCoreSystems/docker-meteor#24]
Hello !

Thanks for your work on meteor + docker.

I do create and launch the image but it fails 
ERR! build error
ERR! stack Error: not found: make

any idea ?

```
mqc_meteor_1  |[0m Installing Meteor latest...
mqc_meteor_1  |[0m Removing your existing Meteor installation.
mqc_meteor_1  |[0m Downloading Meteor distribution
mqc_meteor_1  |[0m
mqc_meteor_1  |[0m Meteor 1.4.1.1 has been installed in your home directory (~/.meteor).
mqc_meteor_1  |[0m Writing a launcher script to /usr/local/bin/meteor for your convenience.
mqc_meteor_1  |[0m
mqc_meteor_1  |[0m To get started fast:
mqc_meteor_1  |[0m
mqc_meteor_1  |[0m   $ meteor create ~/my_cool_app
mqc_meteor_1  |[0m   $ cd ~/my_cool_app
mqc_meteor_1  |[0m   $ meteor
mqc_meteor_1  |[0m
mqc_meteor_1  |[0m Or see the docs at:
mqc_meteor_1  |[0m
mqc_meteor_1  |[0m   docs.meteor.com
mqc_meteor_1  |[0m
mqc_meteor_1  |[0m Building the bundle...(this may take a while)
mqc_meteor_1  |[0m * zodiase:mdl > Settings file ignored: {zodiase:mdl}/zodiase-mdl.json
mqc_meteor_1  |[0m Installing NPM prerequisites...
mqc_meteor_1  |[0m /var/www/bundle/programs/server /src/app
mqc_meteor_1  |[0m npm WARN package.json meteor-dev-bundle@0.0.0 No description
mqc_meteor_1  |[0m npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
mqc_meteor_1  |[0m npm WARN package.json meteor-dev-bundle@0.0.0 No README data
mqc_meteor_1  |[0m npm WARN package.json meteor-dev-bundle@0.0.0 No license field.
mqc_meteor_1  |[0m
mqc_meteor_1  |[0m > fibers@1.0.7 install /var/www/bundle/programs/server/node_modules/fibers
mqc_meteor_1  |[0m > node build.js || nodejs build.js
mqc_meteor_1  |[0m
mqc_meteor_1  |[0m gyp ERR! build error
mqc_meteor_1  |[0m gyp ERR! stack Error: not found: make
mqc_meteor_1  |[0m gyp ERR! stack     at getNotFoundError (/usr/lib/node_modules/npm/node_modules/which/which.js:14

mqc_meteor_1  |[0m gyp ERR! stack     at F (/usr/lib/node_modules/npm/node_modules/which/which.js:69:19)
mqc_meteor_1  |[0m gyp ERR! stack     at E (/usr/lib/node_modules/npm/node_modules/which/which.js:81:29)
mqc_meteor_1  |[0m gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/which.js:90:16
mqc_meteor_1  |[0m gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/node_modules/isexe/index.js:4

mqc_meteor_1  |[0m gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/node_modules/isexe/access.js:

mqc_meteor_1  |[0m gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:82:15)
mqc_meteor_1  |[0m gyp ERR! System Linux 4.4.19-moby
mqc_meteor_1  |[0m gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp
 "rebuild" "--release"
mqc_meteor_1  |[0m gyp ERR! cwd /var/www/bundle/programs/server/node_modules/fibers
mqc_meteor_1  |[0m gyp ERR! node -v v4.5.0
mqc_meteor_1  |[0m gyp ERR! node-gyp -v v3.4.0
mqc_meteor_1  |[0m gyp ERR! not ok
mqc_meteor_1  |[0m Build failed
mqc_meteor_1  |[0m gyp ERR! build error
mqc_meteor_1  |[0m gyp ERR! stack Error: not found: make
mqc_meteor_1  |[0m gyp ERR! stack     at getNotFoundError (/usr/lib/node_modules/npm/node_modules/which/which.js:14

mqc_meteor_1  |[0m gyp ERR! stack     at F (/usr/lib/node_modules/npm/node_modules/which/which.js:69:19)
mqc_meteor_1  |[0m gyp ERR! stack     at E (/usr/lib/node_modules/npm/node_modules/which/which.js:81:29)
mqc_meteor_1  |[0m gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/which.js:90:16
mqc_meteor_1  |[0m gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/node_modules/isexe/index.js:4

mqc_meteor_1  |[0m gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/node_modules/isexe/access.js:

mqc_meteor_1  |[0m gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:82:15)
mqc_meteor_1  |[0m gyp ERR! System Linux 4.4.19-moby
mqc_meteor_1  |[0m gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp
 "rebuild" "--release"
mqc_meteor_1  |[0m gyp ERR! cwd /var/www/bundle/programs/server/node_modules/fibers
mqc_meteor_1  |[0m gyp ERR! node -v v4.5.0
mqc_meteor_1  |[0m gyp ERR! node-gyp -v v3.4.0
mqc_meteor_1  |[0m gyp ERR! not ok
mqc_meteor_1  |[0m Build failed
mqc_meteor_1  |[0m npm ERR! Linux 4.4.19-moby
mqc_meteor_1  |[0m npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
mqc_meteor_1  |[0m npm ERR! node v4.5.0
mqc_meteor_1  |[0m npm ERR! npm  v2.15.9
mqc_meteor_1  |[0m npm ERR! code ELIFECYCLE
mqc_meteor_1  |[0m
mqc_meteor_1  |[0m npm ERR! fibers@1.0.7 install: `node build.js || nodejs build.js`
```

**Comment by Ulexus** [comment]
That is odd.  Are you using the 1.4 tag?

**Comment by Antoine-O** [comment]
my bad. good job !
