### ISSUE TITLE
Bcrypt Fail node v4.5.0 on v1.4 tag branch

### ISSUE THREAD

**Issue by codeHatcher** [CyCoreSystems/docker-meteor#28]
Getting the following error, I'm using the v1.4 tag but still this makes me think it is on the incorrect version of node

```
ndle/lib/node_modules/which/which.js:14:12)
gyp ERR! stack     at F
(/root/.meteor/packages/meteor-tool/.1.4.1_1.139xb76++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/which/which.js:69:19)
gyp ERR! stack     at E
(/root/.meteor/packages/meteor-tool/.1.4.1_1.139xb76++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/which/which.js:81:29)
gyp ERR! stack     at
/root/.meteor/packages/meteor-tool/.1.4.1_1.139xb76++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/which/which.js:90:16
gyp ERR! stack     at
/root/.meteor/packages/meteor-tool/.1.4.1_1.139xb76++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/isexe/index.js:44:5
gyp ERR! stack     at
/root/.meteor/packages/meteor-tool/.1.4.1_1.139xb76++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/isexe/access.js:8:5
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:82:15)
gyp ERR! System Linux 4.4.0-38-generic
gyp ERR! command
"/root/.meteor/packages/meteor-tool/.1.4.1_1.139xb76++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node"                                                                                                       "/root/.meteor/packages/meteor-tool/.1.4.1_1.139xb76++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js"                                                     "rebuild"
gyp ERR! cwd /tmp/mt-1ypnncx/npm/node_modules/.temp-bt0fuk/node_modules/bcrypt
gyp ERR! node -v v4.5.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok                                                                                                       
npm ERR! Linux 4.4.0-38-generic                                                                                       npm ERR! argv                                                                                                         "/root/.meteor/packages/meteor-tool/.1.4.1_1.139xb76++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node"
"/root/.meteor/packages/meteor-tool/.1.4.1_1.139xb76++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/npm"                                                                                                        "rebuild" "--no-bin-links" "--update-binary"
npm ERR! node v4.5.0                                                                                                  npm ERR! npm  v3.10.6                                                                                                 npm ERR! code ELIFECYCLE                                                                                              npm ERR! bcrypt@0.8.6 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bcrypt@0.8.6 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the bcrypt package,                                            npm ERR! not with npm itself.                                                                                         npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild                                                                                         npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs bcrypt                                                                                          npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls bcrypt
npm ERR! There is likely additional logging output above.                                                                                                                                                                                   npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/mt-1ypnncx/npm/node_modules/.temp-bt0fuk/npm-debug.log 
```

**Comment by Ulexus** [comment]
It is showing Node v4.5.0, which is consistent with the requirements of Meteor 1.4.1.  What leads you to believe it is the wrong Node version?

**Comment by codeHatcher** [comment]
The meteor website says the following so I was under the impression we needed 4.4.7

![image](https://cloud.githubusercontent.com/assets/5360982/18772074/b8ee7978-80f8-11e6-98e3-f91e4f1ac871.png)

**Comment by Ulexus** [comment]
No, the release for 1.4.1 explicitly mentions support for Node 4.5.0.

[Announcing Meteor 1.4.1](http://info.meteor.com/blog/announcing-meteor-1.4.1)

**Comment by codeHatcher** [comment]
ok awesome, I also saw the kadira container was using 4.4.7 so wasn't sure

What are your thoughts on the above error?

**Comment by Ulexus** [comment]
I'm not sure; I've gotten worse and worse at debugging node and gyp errors like that.  Could you post the whole log?

**Comment by codeHatcher** [comment]
Yeah, I'll get the logs just now. Also if you are on any other communication platform, I could share my screen so that you don't have to keep going back and forth

**Comment by codeHatcher** [comment]
Having a hard time getting the full logs, I can only copy what is on my screen for some reason and can't page up

```

Cloning into '/src/app'...
Warning: Permanently added the RSA host key for IP address '192.30.253.113' to the list of known hosts.
Switching to branch/tag feature/moveAppDir...
Switched to a new branch 'feature/moveAppDir'
Branch feature/moveAppDir set up to track remote branch feature/moveAppDir from origin.
Forcing clean...
HEAD is now at 13b3979 move app directory to root level
Meteor source found in /src/app/.meteor
Checking Meteor version...
1.4.1
Downloading Meteor install script...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  7786    0  7786    0     0  62527      0 --:--:-- --:--:-- --:--:-- 62790
Installing Meteor 1.4.1.1...
Downloading Meteor distribution

Meteor 1.4.1.1 has been installed in your home directory (~/.meteor).
Writing a launcher script to /usr/local/bin/meteor for your convenience.

To get started fast:

  $ meteor create ~/my_cool_app
  $ cd ~/my_cool_app
  $ meteor

Or see the docs at:

  docs.meteor.com

Building the bundle...(this may take a while)
=> Errors while initializing project:

While loading npm-bcrypt@0.8.6_2...:
error: Command failed:
/root/.meteor/packages/meteor-tool/.1.4.1_1.139xb76++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/npm
rebuild --no-bin-links --update-binary
gyp ERR! build error
gyp ERR! stack Error: not found: make
gyp ERR! stack     at getNotFoundError
(/root/.meteor/packages/meteor-tool/.1.4.1_1.139xb76++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/which/which.js:14:12)
gyp ERR! stack     at F
(/root/.meteor/packages/meteor-tool/.1.4.1_1.139xb76++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/which/which.js:69:19)
gyp ERR! stack     at E
(/root/.meteor/packages/meteor-tool/.1.4.1_1.139xb76++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/which/which.js:81:29)
gyp ERR! stack     at
/root/.meteor/packages/meteor-tool/.1.4.1_1.139xb76++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/which/which.js:90:16
gyp ERR! stack     at
/root/.meteor/packages/meteor-tool/.1.4.1_1.139xb76++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/isexe/index.js:44:5
gyp ERR! stack     at
/root/.meteor/packages/meteor-tool/.1.4.1_1.139xb76++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/isexe/access.js:8:5
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:82:15)
gyp ERR! System Linux 4.4.0-38-generic
gyp ERR! command
"/root/.meteor/packages/meteor-tool/.1.4.1_1.139xb76++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node"
"/root/.meteor/packages/meteor-tool/.1.4.1_1.139xb76++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js"
"rebuild"
gyp ERR! cwd /tmp/mt-1o8appb/npm/node_modules/.temp-10rj6jd/node_modules/bcrypt
gyp ERR! node -v v4.5.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok

npm ERR! Linux 4.4.0-38-generic
npm ERR! argv
"/root/.meteor/packages/meteor-tool/.1.4.1_1.139xb76++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node"
"/root/.meteor/packages/meteor-tool/.1.4.1_1.139xb76++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/npm"
"rebuild" "--no-bin-links" "--update-binary"
npm ERR! node v4.5.0
npm ERR! npm  v3.10.6
npm ERR! code ELIFECYCLE
npm ERR! bcrypt@0.8.6 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bcrypt@0.8.6 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the bcrypt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs bcrypt
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls bcrypt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/mt-1o8appb/npm/node_modules/.temp-10rj6jd/npm-debug.log
gyp ERR! build error
gyp ERR! stack Error: not found: make
gyp ERR! stack     at getNotFoundError
(/root/.meteor/packages/meteor-tool/.1.4.1_1.139xb76++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/which/which.js:14:12)
gyp ERR! stack     at F
(/root/.meteor/packages/meteor-tool/.1.4.1_1.139xb76++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/which/which.js:69:19)
gyp ERR! stack     at E
(/root/.meteor/packages/meteor-tool/.1.4.1_1.139xb76++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/which/which.js:81:29)
gyp ERR! stack     at
/root/.meteor/packages/meteor-tool/.1.4.1_1.139xb76++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/which/which.js:90:16
gyp ERR! stack     at
/root/.meteor/packages/meteor-tool/.1.4.1_1.139xb76++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/isexe/index.js:44:5
gyp ERR! stack     at
/root/.meteor/packages/meteor-tool/.1.4.1_1.139xb76++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/isexe/access.js:8:5
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:82:15)
gyp ERR! System Linux 4.4.0-38-generic
gyp ERR! command
"/root/.meteor/packages/meteor-tool/.1.4.1_1.139xb76++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node"
"/root/.meteor/packages/meteor-tool/.1.4.1_1.139xb76++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js"
"rebuild"
gyp ERR! cwd /tmp/mt-1o8appb/npm/node_modules/.temp-10rj6jd/node_modules/bcrypt
gyp ERR! node -v v4.5.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok

npm ERR! Linux 4.4.0-38-generic
npm ERR! argv
"/root/.meteor/packages/meteor-tool/.1.4.1_1.139xb76++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node"
"/root/.meteor/packages/meteor-tool/.1.4.1_1.139xb76++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/npm"
"rebuild" "--no-bin-links" "--update-binary"
npm ERR! node v4.5.0
npm ERR! npm  v3.10.6
npm ERR! code ELIFECYCLE
npm ERR! bcrypt@0.8.6 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bcrypt@0.8.6 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the bcrypt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs bcrypt
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls bcrypt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/mt-1o8appb/npm/node_modules/.temp-10rj6jd/npm-debug.log

```

**Comment by Ulexus** [comment]
https://hangouts.google.com/hangouts/_/cycoresys.com/meteorstuff

**Comment by Ulexus** [comment]
Okay, this one is easy, too:  it's complaining about `make` not existing.  I've been able to escape without including `build-essentials` so far.  I was hoping I would be able to continue.  Unfortunately, it looks like that is going to force the issue.

**Comment by Ulexus** [comment]
I've just pushed tag `v1.4-build`, which includes the `build-essential` package, which should fix this error.   It increases the size of the image from 280MB to 432MB, so it is fairly substantial, which is why I've _tried_ to avoid it, up to this point and why it is under a separate tag.

I'm not sure about long term plans for this, but give this a try.

**Comment by codeHatcher** [comment]
slowly but surely, getting further along

```
curl: no URL specified!
curl: try 'curl --help' or 'curl --manual' for more information
```
what is that curl request related to?

**Comment by Ulexus** [comment]
Oops; sorry.  Unrelated change.  Fix should be pushed.

**Comment by codeHatcher** [comment]
Fix worked!
